#
#  $$\ $$\           $$\        $$\     $$$$$$$$\
#  $$ |\__|          $$ |       $$ |    $$  _____|
#  $$ |$$\  $$$$$$\  $$$$$$$\ $$$$$$\   $$ |      $$$$$$$\  $$$$$$\  $$$$$$$\   $$$$$$\  $$$$$$\$$$$\  $$\   $$\
#  $$ |$$ |$$  __$$\ $$  __$$\\_$$  _|  $$$$$\   $$  _____|$$  __$$\ $$  __$$\ $$  __$$\ $$  _$$  _$$\ $$ |  $$ |
#  $$ |$$ |$$ /  $$ |$$ |  $$ | $$ |    $$  __|  $$ /      $$ /  $$ |$$ |  $$ |$$ /  $$ |$$ / $$ / $$ |$$ |  $$ |
#  $$ |$$ |$$ |  $$ |$$ |  $$ | $$ |$$\ $$ |     $$ |      $$ |  $$ |$$ |  $$ |$$ |  $$ |$$ | $$ | $$ |$$ |  $$ |
#  $$ |$$ |\$$$$$$$ |$$ |  $$ | \$$$$  |$$$$$$$$\\$$$$$$$\ \$$$$$$  |$$ |  $$ |\$$$$$$  |$$ | $$ | $$ |\$$$$$$$ |
#  \__|\__| \____$$ |\__|  \__|  \____/ \________|\_______| \______/ \__|  \__| \______/ \__| \__| \__| \____$$ |
#          $$\   $$ |                                                                                  $$\   $$ |
#          \$$$$$$  |                                                                                  \$$$$$$  |
#           \______/                                                                                    \______/
#
#
#               Plugin version 5.0
#               Developer: lightPlugins
#
version: 5.4
mysql:
  # if disabled, the plugin will use automatically sqlite for single server setup
  enable: false
  host: 127.0.0.1
  port: 3306
  database: databaseName
  user: username
  password: YourSecretPassword
  ssl: false
  advanced:
    # Don't change any values here if you don't know what you're doing
    connectionPoolSize: 10
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    cachePrepStmts: true
    useServerPrepStmts: true
settings:
  # Debug Messages in the log
  debug: false
  # Start Balance
  start-balance: 200.00
  # Printing first join message to the new Player in Chat (message.yml)
  enable-first-join-message: true
  # Enable the bank modul, so players can use the bank command
  enable-bank-feature: true
  date-format: 'dd:mm:yyyy'
  moneyTopPlaceholderFormat: '#player# '
  # pay comman delay in seconds. Disable this by using 0
  pay-command-delay: 10
  # currency via plural
  currency-name-plural: 'EURs'
  # currency via singular
  currency-name-singular: 'EUR'
  # the max possible money amount. If a player reach this value, he cant get any more money
  max-pocket-balance: 999999999999.99
  # if this is true, numbers from all output messages and lores shows now without decimal places
  currencyWithoutDeciamlPlaces: false
  # the number of players in the baltop command and the baltop placeholders
  baltop-amount-of-players: 10
  # en or disable the players change name update feature
  updatePlayerNameOnJoin: true
  # the players who wohnt be shown in the top command and placeholders
  baltop-exclude:
    - gaben
    - notch
  # The title sound settings. Please use valid spigot sounds in CAPS
  count-up-sound: BLOCK_NOTE_BLOCK_HAT
  final-count-sound: ENTITY_DRAGON_FIREBALL_EXPLODE
  volume: 1.0
  pitch: 1.0
  # The top placeholder format for pocket and bank balances
  #
  # #number# - the number defined in the placeholder itself
  # #name# - the playername comming from lighteconomy
  # #amount# - the amount that the player has in their pocket balance
  # #currency# - the currency comming from "currency-name-plural" in settings.yml
  #
  # You can also use hexcolors like #dc143d
  top-placeholder-format: '&8● &c&l#number#&7# &8● &c#name# &7- &c#amount# &7#currency#'
  # if the top placeholder is not defined
  top-placeholder-not-set: 'none'
  # apply timeRwards to all online players on your server/network
  # the timer starts until the server is loaded
  timeReward:
    money:
      # en- or disable this feature
      enable: false
      # the intervall in seconds the payout is excecuting
      # lightEconomy uses your system time for more performance improve on larg server
      # with many players
      # 600 = 10 min
      intervall: 600
      # the amount of money, online players will receive
      amount: 15
  # If the players pocket is empty, but his bank account has enough money, all transactions
  # from third party plugins will withdraw from their bank account.
  #
  # This is a beta Feature. Use this at your own risk!. Suggested and testet by a community user
  bankAsPocket: false
  # Settings for the %lighteconomy_money_short% and %lighteconomy_bank_balance_short% placeholder
  # You can also use color codes like &c or hex colors like #dc143d
  #
  # #amount# - the formatted amount of money
  # #identifier# - the shortcut letter for the money value like k, m, b, and t
  # #currency# - the moneys currency indicator like EUR and EURs (plural and singular choice automated)
  shortPlaceholderFormat: '&c#amount# &8#identifier# &7#currency#'
  # In English, the point and comma for numbers are used in exactly the opposite way as in German.
  # If you're hosting a German server, disable the internationalDecimals: false.
  internationalDecimals: true
  # Change here the language for your wrong command syntax #commands#
  commandSyntaxTranslation:
    player: 'player'
    target: 'target'
    amount: 'amount'
  # Should players type his value to withdraw/deposit into a fake sign instead of the chat ?
  # Only for the bank gui
  # Requires the latest version of Protocolib
  bankInputViaSign:
    enable: false
    # The first line of the sign is the value input to withdraw/deposit
    # Here you can use all colors inlcuding hexcolor with #dc143d or &#dc143d
    bankSignLine2: '^^^^^^^^^^'
    bankSignLine3: 'Enter Amount'
    bankSignLine4: '0 for cancel'